### ISSUE TITLE
Expose RawTable publically

### ISSUE THREAD

**Issue by hansihe** [rust-lang/hashbrown#104]
I find myself in the need of writing a hash map with some custom ownership semantics in regards to keys.

Your internal `RawTable` seems to provide exactly the functionality I, with enough flexibility to provide the custom semantics I need.

Would you be open to exposing `RawTable` publically, possibly behind a feature flag? I do realize that the API most likely is very unstable and may change, but this is something I would be willing to deal with.

**Comment by Amanieu** [comment]
Could you give a bit more detail regarding the ownership semantics for your hash map?

I'm somewhat open to the idea, but the current `RawTable` API isn't very user-friendly.

**Comment by garro95** [comment]
I would also like it, to have direct (unsafe) access to the entries by index.
The objective would be to replace the current `IndexMap` used inside my [PriorityQueue](https://github.com/garro95/priority-queue/) and remove one level of indirection that I don't need.
