### ISSUE TITLE
Clone without unnecessary allocations

### ISSUE THREAD

**Issue by hbgl** [rust-lang/hashbrown#112]
For my use case I have a worker thread that periodically updates a thread local HashMap and then copies it to another thread. For most iterations no entries are added or removed, only the values change.

I would like to efficiently synchronize the two HashMaps by copying the arrays of control bytes and elements directly to the already allocated arrays of the other HashMap. Basically it would be the same thing that's done in RawTable's `clone` function without the extra allocations.

https://github.com/rust-lang/hashbrown/blob/bacb169740fe04c6f0734d3b43bc5482de040ab6/src/raw/mod.rs#L978-L1028

I saw that the RawTable was recently exposed in #104 but unless I missed something it is not enough to copy the contents from one map into another. Do you think it would be a good idea to implement  [clone_from](https://doc.rust-lang.org/std/clone/trait.Clone.html#method.clone_from) on RawTable which reuses the arrays if possible?

**Comment by Amanieu** [comment]
Note that you can somewhat already do this:
```rust
dest.clear();
dest.extend(src.iter().map(|(k, v)| (k.clone(), v.clone())));
```
This should avoid any unnecessary allocations in most cases.

**Comment by hbgl** [comment]
I thought that copying the underlying buffer would be more efficient especially since my keys are very small (i64). Do you think that implementing `clone_from` makes sense for a HashMap at all? I feel that not being able to copy the underlying buffer wastes one of the main advantages of the Swiss Table.

**Comment by Amanieu** [comment]
Copying the buffer only works if both tables have the exact same allocation size. We could resize the destination table to match the source table, but that feels wasteful when the destination table is larger than the source.

**Comment by hbgl** [comment]
> Copying the buffer only works if both tables have the exact same allocation size. We could resize the destination table to match the source table, but that feels wasteful when the destination table is larger than the source.

Okay I didn't think about that one. This wouldn't happen for my case but it's definitely a no-go for `clone_from`.

I'll stick with
> ```rust
> dest.clear();
> dest.extend(src.iter().map(|(k, v)| (k.clone(), v.clone())));
> ```

Thanks for your time.

**Comment by itamarst** [comment]
I am in similar situation, I have two hashmaps A and B, A gets inserts and removals, and every once in a while A is cloned into B. So B is usually fairly similar to A.

For now I'm using an immutable hashmap (from `im`) where clone() is cheap, but that has its own costs of additional overhead for inserts and removals.
