### ISSUE TITLE
Getting EXC_I386_GPFLT on custom heap memory allocator

### ISSUE THREAD

**Issue by shisoft** [rust-lang/hashbrown#126]
I built a simple memory allocator and set it as global. When I tried to run the test, I got `EXC_BAD_ACCESS (code=EXC_I386_GPFLT)` under Mac OS X. 

This is the stack
```
hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h89b32432d29be057 0x000000010bba88b1
hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h89b32432d29be057 0x000000010bba88b1
hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h89b32432d29be057 0x000000010bba88b1
hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h89b32432d29be057 0x000000010bba88ac
hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h89b32432d29be057 0x000000010bba88a5
hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h89b32432d29be057 0x000000010bba886c
term::terminfo::parser::compiled::parse::hbece3b8f1d06cb9e 0x000000010b95a974
```

This is the what I see in the disassembler
```
hashbrown::raw::RawTable$LT$T$GT$::reserve_rehash::h89b32432d29be057:
	movdqa (%r15), %xmm0
```

I assume I did not get the alignment right for `movdqa` instruction, but content of `r15` is `0x000000011355f858` when the mmap returned address is `0x0000000113559000`

The code to my allocator is at 
https://github.com/ShisoftResearch/Nulloc/blob/a28b93b3647b9628a4c3d247d52257a88a756cd8/src/bump_heap.rs

**Comment by Amanieu** [comment]
Your allocator doesn't respect the alignment from the `Layout`. You need to align `current_tail` before allocating.

**Comment by shisoft** [comment]
@Amanieu Thanks, that is exactly my problem
