### ISSUE TITLE
Confused about aHash DOS resistance

### ISSUE THREAD

**Issue by sbstp** [rust-lang/hashbrown#127]
The README on this repo claims that aHash is not DOS resistant but on the aHash repo it claims that it is DOS resistant. 

> Goals
AHash is intended to be the fastest DOS resistant hash for use in HashMaps available in the Rust language. Failing in any of these criteria will be treated as a bug.

**Comment by Amanieu** [comment]
Basically, we reserve the right to change the hash function in the future to one which may not be DOS resistant.

**Comment by sbstp** [comment]
Ah ok I think I get it. aHash is DOS resistant but hashbrown's default hash function might not always be aHash or something DOS resistant?
