### ISSUE TITLE
[question] How to configure the stdlib to be fast?

### ISSUE THREAD

**Issue by jabbalaci** [rust-lang/hashbrown#131]
I made a test with the stdlib's hashmap and with this one, hashbrown. The hashbrown version was much faster. In the doc., it's written that the stdlib now uses hashbrown. I guess the stdlib with hashbrown uses a different hash function, which must be slower.

My question: if I want to use the stdlib's hashbrown, how can I configure it to be just as fast as if I had used hashbrown as a dependency?

I don't need DOS-resistance. I just need a very fast hashmap. Thanks.

**Comment by Amanieu** [comment]
You can use `FxHashMap` or `AHashMap` which are aliases of the libstd hashmap with custom hashers. They can be found in the `ahash` and `rustc-hash` crates.

**Comment by jabbalaci** [comment]
Thanks @Amanieu . I also found https://crates.io/crates/fxhash , which seems to be the same as https://crates.io/crates/rustc-hash . Which one to use?

I could try FxHashMap since I found examples for it. However, AHashMap doesn't provide any code snippets. How could I try it? Do you have an example for it?

**Comment by Amanieu** [comment]
AHashMap is used exactly the same way as FxHashMap.

**Comment by jabbalaci** [comment]
For FxHashMap, this works:

```
use rustc_hash::FxHashMap;
let map: FxHashMap<u32, u32> = FxHashMap::default();
```

I tried this with ahash but had no luck:

```
use ahash::AHashMap;
let map: AHashMap<u32, u32> = AHashMap::default();
```

**Comment by Amanieu** [comment]
Try `AHashMap::new` instead.

**Comment by jabbalaci** [comment]
I get this error:

```
2 | use ahash::AHashMap as HashMap;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `AHashMap` in the root
```

Cargo.toml is OK:

```
[dependencies]    
ahash = "0.2"
```

**Comment by Amanieu** [comment]
You need to enable the `std` feature in Cargo.toml:
```
ahash = {version = "0.2", features = ["std"]}
```

**Comment by jabbalaci** [comment]
Thanks @Amanieu , it works now!
