### ISSUE TITLE
drain_filter for hashmaps?

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/hashbrown#134]
Hi,

I saw the RFC for https://github.com/rust-lang/rust/issues/43244, and was wondering if there was an equivalent need for `drain_filter`-esque behaviour with hashmaps? I've thought about using drain and then reconstructing another HashMap, but I would like to avoid the cost of that.

I also thought about using retain and putting items that weren't retained into a `Vec`, but I can't take ownership of the items being removed unless I clone/copy them.

In this case, I'm trying to minimize the number of allocations I'm making while taking some items out of a hashmap and putting them into a buffer passed in from elsewhere. The main issue with the retain approach is the inability to not take ownership.

I might be able to dig into the `raw` api to get something, but I was wondering if this was common enough to be added to the safe api.

I can't seem to find another RFC for this anywhere, and I'm not sure if this is the relevant place to request this, but I thought since this was the underlying implementation for the hashmap it would be good to request it here.

Thanks!

**Comment by Amanieu** [comment]
Porting `drain_filter` to `HashMap` shouldn't be too difficult if you base it on the implementation of `retain`. I don't think there would be any objections to adding this feature. Feel free to submit a PR here first, and in libstd afterwards.
