### ISSUE TITLE
Performance drop after upgrading from v0.3

### ISSUE THREAD

**Issue by akshaydewan** [rust-lang/hashbrown#142]
Recently we upgraded hashbrown from 0.3 to 0.6.3 and noticed a drop in performance. (For context, the program is a simulation that needs to perform several million lookups over the course of the run).

Here's a small program to measure the numbers:

```rust
use std::time::Instant;

use hashbrown::HashMap;
use rand::{Rng, thread_rng};

const MAP_SIZE: i32 = 1000_000;
const LOOKUP_ITEMS: usize = 1000_000;

fn main() {
    let mut map: HashMap<i32, i32> = HashMap::new();
    for i in 0..MAP_SIZE {
        map.insert(i, i);
    }
    test(map);
}

fn test(hashmap: HashMap<i32, i32>) -> Vec<i32> {
    let mut lookup = Vec::with_capacity(LOOKUP_ITEMS);
    for _ in 0..LOOKUP_ITEMS {
        lookup.push(thread_rng().gen_range(0, MAP_SIZE));
    }
    let start = Instant::now();
    let filtered_list = lookup.into_iter().filter(|key| { hashmap.contains_key(&key) }).collect();
    println!("Filtered in {} ms", start.elapsed().as_millis());
    filtered_list
}
```

Here's the output from v0.3 for 10 runs:
```
Filtered in 19 ms
Filtered in 19 ms
Filtered in 20 ms
Filtered in 20 ms
Filtered in 17 ms
Filtered in 19 ms
Filtered in 19 ms
Filtered in 19 ms
Filtered in 19 ms
Filtered in 20 ms
```

Here's the output from v0.6.3 for 10 runs
```
Filtered in 29 ms
Filtered in 28 ms
Filtered in 28 ms
Filtered in 27 ms
Filtered in 29 ms
Filtered in 29 ms
Filtered in 29 ms
Filtered in 28 ms
Filtered in 29 ms
Filtered in 27 ms
```

I noticed that 0.7.0 was released today, and I see that it has some improvement over 0.6.3 (awesome!)
```
Filtered in 22 ms
Filtered in 23 ms
Filtered in 23 ms
Filtered in 23 ms
Filtered in 24 ms
Filtered in 23 ms
Filtered in 23 ms
Filtered in 24 ms
Filtered in 24 ms
Filtered in 24 ms
```

However 0.3 still was faster. Does anyone know the reason for the reduced performance and was it expected?

Additional info:
- cargo 1.40.0 (bc8e4c8be 2019-11-22)
- rustc 1.40.0 (73528e339 2019-12-16)
- Environment: MacOS 10.14.6

I'm new to rust and systems programming in general. Any help would be appreciated. Thanks!

**Comment by Amanieu** [comment]
I think it's just because we changed the default hasher from FxHash to AHash.

**Comment by Amanieu** [comment]
To be precise: v0.5.1 changed the default hasher from FxHash to AHash. v0.7.0 updated AHash from 0.2 to 0.3, which could explain the performance improvement.

**Comment by akshaydewan** [comment]
Thanks, that makes sense. I understand that AHash is faster for most use cases, so I'll close this issue. As for my case, I've switched to FxHash for now.
