### ISSUE TITLE
HashMap::get_key_value_mut?

### ISSUE THREAD

**Issue by dodomorandi** [rust-lang/hashbrown#144]
I found myself needing a _partially mutable_ version of `HashMap::get_key_value`, with the following signature:
```rust
pub fn get_key_value_mut<Q: ?Sized>(&mut self, k: &Q) -> Option<(&K, &mut V)> where
    K: Borrow<Q>,
    Q: Hash + Eq, 
```
Obviously I was looking at `std`, and I think I cannot obtain nothing similar without the unstable `hash_raw_entry` API. However, `hashbrown` currently supports the API, therefore it should be pretty straightforward to implement the new feature.

The only thing I am still doubtful is the possibility of creating of an inconsistent state with the proposed API. At first glance, it should not be possible to smash the state of the hashmap, but maybe I am missing something. What do you think?

**Comment by Amanieu** [comment]
I think this is a reasonable addition to the API. I am happy to accept a PR for it.

**Comment by Amanieu** [comment]
Actually you can already do this with the existing API by using `entry()`, matching an `OccupiedEntry` and then calling `key` and `get_mut`.

**Comment by dodomorandi** [comment]
> Actually you can already do this with the existing API by using `entry()`, matching an `OccupiedEntry` and then calling `key` and `get_mut`.

The issue with that, if I am not wrong, is that `get_mut` cannot be used because there is already a borrow of `self` for the call to `key`.

> I think this is a reasonable addition to the API. I am happy to accept a PR for it.

Of course! I see that `HashMap::get_key_value` directly uses `table.find` with a bit of `unsafe`. It is ok if I follow the same approach?

**Comment by Amanieu** [comment]
> The issue with that, if I am not wrong, is that get_mut cannot be used because there is already a borrow of self for the call to key.

Ah yes, I forgot about that.

> Of course! I see that HashMap::get_key_value directly uses table.find with a bit of unsafe. It is ok if I follow the same approach?

Sure, that's fine.
