### ISSUE TITLE
Consider disabling ahash-compile-time-rng by default

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/hashbrown#149]
Just registering https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/Determinism.20in.20const.20eval/near/192178710.

> @Amanieu is considering just disabling the "ahash-compile-time-rng" feature by default since so many people are complaining about it...

As one data point, apparently libstd already opts out of compile-time-rng. https://github.com/rust-lang/rust/blob/1.42.0/src/libstd/Cargo.toml#L26

**Comment by Amanieu** [comment]
This was done in #155.
