### ISSUE TITLE
Should RawTable::{into_iter, par_iter, into_par_iter, par_drain} be marked unsafe?

### ISSUE THREAD

**Issue by andersk** [rust-lang/hashbrown#156]
I think the current implementations of `RawTable::into_iter`, `RawTable::par_iter`, `RawTable::into_par_iter`, and `RawTable::par_drain` need to be marked `unsafe` for the same reason that `RawTable::iter` and `RawTable::drain` already are.

**Comment by andersk** [comment]
Alternatively, since the `RawTable` API is experimental, is it crazy to suggest changing it to be entirely safe using lifetimes, given that `unsafe` users who really need to break the borrow checker can already do so using `transmute` and so on? For context, I used the `RawTable` API to build an interner that converts between large objects and small integers without storing multiple copies of the large objects. It needs `RawTable` for the custom hash function that does a lookup in a separate `Vec`, but there’s no fundamental reason it should need `unsafe`:

```rust
use ahash::AHasher;
use hashbrown::raw::RawTable;
use std::hash::{Hash, Hasher};

pub type Id = u32;

pub struct Interner<T> {
    values: Vec<T>,
    ids: RawTable<Id>,
}

fn value_hash<T: Hash>(value: &T) -> u64 {
    let mut hasher = AHasher::default();
    value.hash(&mut hasher);
    hasher.finish()
}

fn id_hasher<'a, T: Hash>(values: &'a [T]) -> impl 'a + Fn(&'_ Id) -> u64 {
    move |&id| value_hash(&values[id as usize])
}

impl<T> Default for Interner<T> {
    fn default() -> Interner<T> {
        Interner {
            values: vec![],
            ids: RawTable::new(),
        }
    }
}

impl<T: Eq + Hash> Interner<T> {
    pub fn intern(&mut self, value: T) -> Id {
        let hash = value_hash(&value);
        if let Some(bucket) = self.ids.find(hash, |&id| self.values[id as usize] == value) {
            unsafe { *bucket.as_ref() }
        } else {
            let id = self.values.len() as Id;
            self.values.push(value);
            self.ids.insert(hash, id, id_hasher(&self.values));
            id
        }
    }

    pub fn get(&self, id: Id) -> &T {
        &self.values[id as usize]
    }
}
```

**Comment by Amanieu** [comment]
You're right, those methods should be unsafe. Would you like to prepare a PR?

Regarding `RawTable`, I would prefer keeping lifetimes out of it. Instead, have you considered using the safe `raw_entry` API for your interner?

**Comment by andersk** [comment]
`into_par_iter` may actually be okay, since `RawIntoParIter` owns the table rather than just pointing into it. Opened #157 for the other three.

**Comment by andersk** [comment]
You’re right that `raw_entry_mut` suffices in my case. I had failed to notice `RawVacantEntryMut::insert_with_hasher` since there’s no `RawEntryMut::or_insert_with_hasher`. Thanks!
