### ISSUE TITLE
How to remove a borrowed value from the map

### ISSUE THREAD

**Issue by Plecra** [rust-lang/hashbrown#158]
After searching for a value, I need to move the value that I've found out of the map. I can't use the `drain_filter` API because the result depends on the other entries in the map:

```rust
let map = HashMap::new();

if let Some((key, _)) = map.iter().min_by(|(_, a), (_, b)| a.cmp(b)) {
    let value = map.remove(key).unwrap();
    // Error: `map` and `key` alias each other
}
```

Is there a way to do this?

**Comment by Amanieu** [comment]
You need to make a copy of the key and pass that to `remove`.

**Comment by Plecra** [comment]
😄 Well sure, that would solve the problem. I'd rather avoid the `Clone` bound on my generic implementation, and it seems wasteful to find the bucket again.

Is there some reason this wouldn't be compatible with the actual implementation of the `HashMap`? I was thinking about trying to implement something myself, but this some arcane magic to me 👀

**Comment by Amanieu** [comment]
Unfortunately you can't mutate the `HashMap` while holding a reference to a value inside it. Rust's borrow checker won't allow it.

**Comment by Plecra** [comment]
My bad, I see how the question was misleading. I'm imagining a version of the HashMap API that would allow this with a `delete` method on the `Entry` API. Then something like a `fold` method on the `HashMap` would allow you to retrieve the entry you want to manipulate.

It'd be a big change to the `hashbrown` library, but if I wanted to write my own version of this, would it be possible to base it on a fork of this code?

**Comment by Amanieu** [comment]
You could probably make something work with the unsafe RawTable API.
