### ISSUE TITLE
 ^^^ use of undeclared type or module `std` : use std::hint::unreachable_unchecked;

### ISSUE THREAD

**Issue by rohitjoshi** [rust-lang/hashbrown#160]
I am getting following error with the recent version of hashbrown due to a bug in `ahash-0.3.7`. When I switch to `hashbrown 0.6.3` which uses `ahash v0.2.18` works fine.

I use mac book pro / Catalina. Rust version: rustc 1.46.0-nightly (0262de554 2020-06-07)

` RUSTFLAGS="-C target-cpu=native" cargo build --release`

```
failed to resolve: use of undeclared type or module `std`
 --> /Users/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/ahash-0.3.7/src/aes_hash.rs:4:5
  |
4 | use std::hint::unreachable_unchecked;
  |     ^^^ use of undeclared type or module `std`
```

**Comment by rohitjoshi** [comment]
When I comment out [use std::hint::unreachable_unchecked ] (https://github.com/tkaitchuck/aHash/blob/master/src/aes_hash.rs#L4), it compiles fine.

**Comment by Amanieu** [comment]
https://github.com/tkaitchuck/aHash/issues/36

**Comment by Amanieu** [comment]
This should be fixed now.
