### ISSUE TITLE
Doc request: what modification is allowed to RawTable while holding RawIter

### ISSUE THREAD

**Issue by CAD97** [rust-lang/hashbrown#165]
More context [on urlo](https://users.rust-lang.org/t/hashbrown-help-concurrent-iteration-and-modification/44637) and [my questionable code](https://github.com/CAD97/sorbus/pull/53).

What operations are allowed on [`RawTable`](https://docs.rs/hashbrown/0.8.0/hashbrown/raw/struct.RawTable.html) while holding a [`RawIter`](https://docs.rs/hashbrown/0.8.0/hashbrown/raw/struct.RawIter.html)?

Per my reading, the implementation currently suggests:

- Required(?) for exposed behavior:
  - non-mutating inspection of the `RawTable`
  - [`erase`ing](https://docs.rs/hashbrown/0.8.0/hashbrown/raw/struct.RawTable.html#method.erase_no_drop) the most recently yielded `Bucket`
- Definitely not allowed (UB):
  - anything that causes a reallocation
  - erasing a bucket "ahead" of the iterator that has yet to be yielded
- Potentially allowed:
  - erasing a bucket "behind" the iterator head that has previously been yielded but is not the most recently yielded bucket

I would benefit from the above "delayed erasing" being guaranteed sound (for the use case linked above).

Side note: it would be useful to make [`RawIter`'s `debug_assert` that it iterated all the expected items](https://github.com/rust-lang/hashbrown/blob/efbd03661fc9df0e594ecc89784107353cc71060/src/raw/mod.rs#L1409) say what went wrong. Something simple like "exhausted iterator before expected; this likely indicates modification of a hash table while iterating it, which is UB" would definitely make hitting that assertion more obvious than the default message of "200 != 0" from inside of hashbrown's internals.

**Comment by Amanieu** [comment]
This feels like something extremely fragile to rely on since we could, for example, in the future decide to iterate backwards because we've changed our internal representation.

Looking at your code, is it really necessary to process the `to_drop` list while iterating? Can't you just process that list after the initial iteration to find dead "roots" has finished?

**Comment by CAD97** [comment]
Yeah, after sleeping on it, I realize that doing that would work, and do so without any impact on asymptotic complexity or space usage, and negligible impact on actual space usage.

It'd still probably be nice to say what's guaranteed to work: at the least, erasing the bucket most recently yielded by the iterator needs to be allowed for `retain` to work IIUC.

**Comment by jonhoo** [comment]
@CAD97 I'm not sure if it's relevant to your use-case, but https://github.com/rust-lang/hashbrown/pull/167 may be of interest to you.
