### ISSUE TITLE
Document erase_no_drop guarantees

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/hashbrown#168]
Following some discussion in https://github.com/bluss/indexmap/pull/131#discussion_r447965041, it'd be good to document the contract of `erase_no_drop`. In particular, there is code both inside `hashbrown` and in the pending PR to `indexmap` (https://github.com/bluss/indexmap/pull/131) along the lines of:
```rust
let v = unsafe {
    table.erase_no_drop(&bucket);
    bucket.read()
}
```
This, by first reading, seems like it shouldn't be okay. `erase_no_drop` erases the bucket, so why is it okay to read from it after the fact? It [turns out](https://github.com/bluss/indexmap/pull/131#discussion_r447980041), probably unsurprisingly, that `hashbrown` indeed currently supports this sequence of operations; `erase` only erases the bucket in the control bytes, but does not otherwise invalidate the bucket.

I think we have a choice to make: either we add this as a guarantee to the documentation of `erase_no_drop` so that callers can rely on that detail of the implementation, _or_ we do not give that guarantee, and require callers to always access the bucket _before_ they erase it. The latter gives us more leeway to change `erase_no_drop` later, at the cost of slightly less convenient access for callers. Of course _internally_ it's fine for `hashbrown` to rely on being able to access the bucket after `erase_no_drop` is called. This is a question of what the public contract (which we cannot break without a breaking release) should be.

**Comment by cuviper** [comment]
Do we need a similar clarification on `clear_no_drop`?

In theory, you could have a outstanding `Bucket` live across this and still want to read it afterward, but I don't see anything that's actually doing that right now.

**Comment by jonhoo** [comment]
Yes, I think the same clarification is needed there

**Comment by Amanieu** [comment]
`erase_no_drop` is deprecated and replaced by `erase` and `remove` so I'm going to close this.
