### ISSUE TITLE
Public version of RawTable::try_with_capacity

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/hashbrown#169]
We already expose `RawTable::try_reserve`, but do not expose `RawTable::try_with_capacity`. The latter should probably also be public (though without the `fallible` argument).

**Comment by Amanieu** [comment]
I don't have any objection to exposing this as well.

**Comment by jonhoo** [comment]
Fixed in https://github.com/rust-lang/hashbrown/pull/174
