### ISSUE TITLE
Optin to store key hashes

### ISSUE THREAD

**Issue by arthurprs** [rust-lang/hashbrown#17]
I wonder how much of an overhead would be to store hash codes to prevent the worst case [1].

This would be nice as an optin as there's an obvious trade-off with this: memory overhead and insert performance on fully pre allocated tables would be worse.

[1] resizing hash tables which keys are somewhere else in memory (strings) and/or are hard to hash and/or the hasher is slow (like sip).

**Comment by lachlansneff** [comment]
It should be possible to write a wrapper type that caches the hash.

**Comment by Amanieu** [comment]
> It should be possible to write a wrapper type that caches the hash.

Sort of, but it wouldn't be very good. The problem with that approach is that the wrapper type does not know what hasher the table is using, it just implements `Hash` which is generic over all `Hasher`s. Only the `HashMap` can calculate the final hash value that is used to index the table.

**Comment by arthurprs** [comment]
Having this as a feature flag should be easy but it should also be doable with a trait/specialization. It's only a 4/8 bytes store at the end of the insert function (a potential cache miss), which can be used fetched during resizes.

**Comment by arthurprs** [comment]
Closing as I think this doesn't matter in the vast majority of cases.
