### ISSUE TITLE
`drain_filter` has opposite behavior of standard library version

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/hashbrown#186]
In methods like [`std::vec::Vec::drain_filter`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.drain_filter), the element is removed if the closure returns `true`.  But in `hashbrown::HashMap::drain_filter` (#135) and `hashbrown::HashSet::drain_filter` (#179), the element is removed if the closure returns `false`.  😦 

cc rust-lang/rust#59618

**Comment by Amanieu** [comment]
That... seems unfortunate. I assume the proper behavior is the one in libstd and the behavior of hashbrown is incorrect.

This is going to have to be a (silent) breaking change, but that's fine since we can just do a major version bump.
