### ISSUE TITLE
Removing OccupiedEntry and get back a VacantEntry

### ISSUE THREAD

**Issue by SkiFire13** [rust-lang/hashbrown#189]
Right now there's no way to remove a value from an `OccupiedEntry` getting back both the value removed and a `VacantEntry` for the key just removed. I propose to add something like

```rust
fn take(self) -> (V, VacantEntry<'a, K, V, S>)
```

to `OccupiedEntry`. However I'm not sure how this could be implemented without changing how `VacantEntry` works.

The use I have for this would be temporary removing a value from the map without needing 2 lookups. Right now I have to `remove` (1st lookup) the value, doing what I want to do with that and then `insert` (2nd lookup) it again. If I could reuse the fact that the `OccupiedEntry` had a valid bucket for that key I could skip a lookup in the map.

**Comment by Amanieu** [comment]
Have you tried using a crate like [`take_mut`](https://crates.io/crates/take_mut)?

**Comment by SkiFire13** [comment]
I already knew about take_mut but it doesn't work in my case because:

- I need to provide a fallback value (and I can't) or in case of panics it will abort. With my proposal the map should be left in a consistent state so no `catch_unwind` or `abort` is needed.
- In my use case I may or may not use the `VacantEntry` depending on the result of a computation involving the value I previously took, but `take_mut` forces me to put back a value.

To be fair [a workaround](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ad76e9f45f5fbf98db91ea5d24cea45c) inspired by `take_mut` should be possible but it requires you to write `unsafe` code and still need `catch_unwind` because the map isn't left in a truly valid state. I'm also not sure that this code is correct (in particular possible shenanigans that may happen with `catch_unwind`), so I would prefer not having to write it myself.
