### ISSUE TITLE
Hashbrown is broken 

### ISSUE THREAD

**Issue by ShaleXIONG** [rust-lang/hashbrown#206]
Hashbrown 0.6.3 causes a problem due to its dependency, ahash
```
error: failed to select a version for the requirement `ahash = "^0.2.11"`
  candidate versions found which didn't match: 0.4.5, 0.4.4, 0.4.3, ...
  location searched: crates.io index
required by package `hashbrown v0.6.3`
    ... which is depended on by `pinecone v0.2.3 (/Users/shaxio01/git/pinecone)`
```
I tried bumping up hashbrown to v0.7 and it passed all the tests on my machine, with `nightly-2020-05-07-x86_64-apple-darwin`.

**Comment by Amanieu** [comment]
This is happening because old versions of `ahash` have been yanked. You should update your `hashbrown` dependency to the latest version which is 0.9.1.

**Comment by ShaleXIONG** [comment]
Cool I will contact the pinecone maintainers.
