### ISSUE TITLE
Table memory layout

### ISSUE THREAD

**Issue by eggyal** [rust-lang/hashbrown#250]
I'm curious why tables are laid out with buckets followed by control bytes, rather than the other way around?  I think this must have been a deliberate choice because it can lead to more padding than might have been required if the control bytes came first, but I can't quite see what the thinking was.

I ask because I'm attempting to implement statically sized Swiss Tables (that can reside on the stack), using the min const generics feature that's anticipated to very shortly become available in stable Rust v1.51 (aside: would such an implementation be welcome as a PR to this crate?)—and I wonder if this layout was chosen for optimisations associated with dynamic sizing that can be disregarded in the static case?

**Comment by Amanieu** [comment]
Control bytes are aligned to 16 bytes to allow for SIMD optimizations, while data is typically only aligned to 8 bytes. This layout was chosen to minimize padding.

**Comment by eggyal** [comment]
Thanks, that makes sense—I had been considering particularly degenerate, unrealistic sizes and alignments.
