### ISSUE TITLE
assertion failed: self.bucket_mask < Group::WIDTH

### ISSUE THREAD

**Issue by s1341** [rust-lang/hashbrown#256]
Hi,

When running in debug, I'm occasionally getting this assert.

```
thread 'main' panicked at 'assertion failed: self.bucket_mask < Group::WIDTH', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.11.2/src/raw/mod.rs:1229:25
```

I checked with a debugger, and the `bucket_mask` is `0x3ff`.

**Comment by Amanieu** [comment]
Can you create an example program which reproduces this issue?

**Comment by s1341** [comment]
Haven't been able to reproduce... I think it might have been due to memory corruption. I'm going to close for now.
