### ISSUE TITLE
Very minor performance tweak

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/hashbrown#262]
I noticed that there's an `if capacity == 0` switch inside `fallible_with_capacity()`. I've currently got a use case for RawTable where it is created with a fixed, non-zero capacity. It'd be nice to be able to pass `NonZeroUsize` as a capacity type as well as `usize`, so this `if` isn't hit. Should be possible by implementing a trait (eg `Capacity`) that `NonZeroUsize` and `usize` implement.

The performance implications are very minor, but, the more places that can take advantage of non-zero types, IMV, the better, for Rust, as it encourages their wider use and adoption.

**Comment by Amanieu** [comment]
I think the increased API complexity largely outweighs any benefits that could be gained from this.

**Comment by raphaelcohn** [comment]
I'd disagree the API is more complex, but it's your project and your call.
