### ISSUE TITLE
Document the rare cases in which `RawIterHash` 'may return a bucket with a different hash'

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/hashbrown#263]
Document the rare cases in which `RawIterHash` 'may return a bucket with a different hash'.

This is useful to know if one can design a key with a hash such that it does not need to be present in `RawTable`'s `<T>` - or at least make it clear it is not possible!

For instance, I've got an use case where every hash will always be unique (perfect); it'd be nice to reduce my storage costs by half.

**Comment by Amanieu** [comment]
`hashbrown` only stores 7 bits of the hash in the table. `RawIterHash` will return any entry for which those 7 bits match.

**Comment by raphaelcohn** [comment]
I think it'd be useful to put those comments into the docs for the structures and functions used. The description as it stands implies it is a possibility; the reality is that it will always occur in 1 in 128 cases.

@Amanieu I'm not sure I fully understand the comment about 7 bits, since a hash is provided as 64 bits. Which bits are discarded or kept?

**Comment by Amanieu** [comment]
https://github.com/rust-lang/hashbrown/blob/805b5e28ac7b12ad901aceba5ee641de50c0a3d1/src/raw/mod.rs#L149

**Comment by raphaelcohn** [comment]
Thank you - I can follow that.

**Comment by raphaelcohn** [comment]
Surely the `& 0x7f` isn't needed on a 64-bit platform as a right shift would have shifted in 0 bits?

**Comment by Amanieu** [comment]
LLVM is smart enough to optimize the `& 0x7f` away since it knows that `top7` is only 7 bits wide.

I am not sure how I can improve the documentation for that method. Do you have any ideas for specific wording that would make the description clearer?

**Comment by raphaelcohn** [comment]
Optimization - it may do so, but then it's just a matter of style as to whether the intent is clearer or not. Personally, I'd use a `#cfg`, but that's a very debatable pointer. It's effectively moot. Likewise I prefer to bracket my operators `hash_len * 8 - 7`, as I never remember operator orderings when switching languages... and it saves everyone maintaining the code to be 100% proficient, too.

Replace 'rare cases' with something like "For every ¹/₁₂₈ᵗʰ of possible hash values, it is possible for this iterator to return a bucket for a different hash value. This is because internally the iterator uses only the top most bits to select a hash bucket. On a platform where `usize` is 64-bits wide, only the top most 7 bits are used (bits at zero-based indices 63 to 56 inclusive). On a platform where `usize` is 32-bits wide, only the 7 bits at zero-based indices 31 to 24 inclusive are used".

That wording assumes I've interpreted the `h2()` function code correctly (;-).

**Comment by raphaelcohn** [comment]
Seen the pull request - I presume you want to use less detail to maintain some flexibility in implementation choice in the future?

As an aside, I was wondering if the use of the topmost 7 bits does need to be highlighted elsewhere, eg in the consumer's choice of hash values or hash functions, to avoid excessive probing? For example, using anything pointer like seems like it could be problematic, as these values on x86-64 are going to be unique only in the lowest 47 bits.
