### ISSUE TITLE
Pointer arithmetic UB in very large tables

### ISSUE THREAD

**Issue by Radbuglet** [rust-lang/hashbrown#264]
`RawTable` seems to have an implicit invariant that the size of the table's allocation will never exceed `isize::MAX`, an invariant which becomes important for ensuring the safety of raw pointer [`.add` calls](https://doc.rust-lang.org/std/primitive.pointer.html#method.add). This invariant, however, is not properly enforced.

Allocating a table with a `usize::MAX` capacity fails as expected because [`capacity_to_buckets`](https://github.com/rust-lang/hashbrown/blob/805b5e28ac7b12ad901aceba5ee641de50c0a3d1/src/raw/mod.rs#L194) multiplies this value by `8` in a checked fashion. The highest capacity a user can request is thus `usize::MAX / 8`, which produces a bucket count of `(usize::MAX / 7).next_power_of_two()`, or `isize::MAX / 2`.

This bucket count is then passed on to [`TableLayout::calculate_layout_for`](https://github.com/rust-lang/hashbrown/blob/805b5e28ac7b12ad901aceba5ee641de50c0a3d1/src/raw/mod.rs#L251), which calculates the `ctrl_offset` using exclusively checked arithmetic. However, the maximum size of values being processed in `calculate_layout_for` is `usize::MAX`, not `isize::MAX`. Thus, users can get `ctrl_offsets` and `sizes` greater than `isize::MAX` by requesting tables with bucket sizes greater than `2` bytes.

If the allocator somehow manages to fulfill a request for more than `isize::MAX` bytes, [the next line](https://github.com/rust-lang/hashbrown/blob/805b5e28ac7b12ad901aceba5ee641de50c0a3d1/src/raw/mod.rs#L1166) will instantly UB as it is offsetting the allocation pointer by `ctrl_offset` bytes, a value which can be greater than `isize::MAX`.

This is, of course, an *incredibly rare* situation and I doubt any real world applications will benefit from the extra safety guarantee. Nonetheless, this sort of unsound behavior was important enough for [`std`'s docs](https://doc.rust-lang.org/std/primitive.pointer.html#method.add) to call attention to it and for `Vec` to apparently handle this scenario.

I haven't looked at all the other resizing/reallocation logic so it might be worth clarifying certain state invariants for the table sizes and ensuring that they're maintained throughout `RawTable`'s implementation.

**Comment by Amanieu** [comment]
Nice catch!

Looking at the code, I think the best place to fix this with minimal overhead would be in `capacity_to_buckets`: we could simply change the code to `cap.checked_mul(16)? / 14` which should will cause the overflow check to reject too-large tables.

Could you open a PR for this? You can also add more comments to clarify the invariants where needed.

**Comment by Radbuglet** [comment]
Updating `capacity_to_buckets`'s to limit the maximum requestable bucket count will not fix the issue since users control the size of the buckets and can thus always grow any non-zero bucket count to a value greater than `isize::MAX`. The fix will have to limit the size of the table in bytes, not its bucket count.

As for the structure's invariants, I think the only requirement is that the size of the table has to be less than `isize::MAX`. ZSTs introduce slight logical complications in how they are treated as having a size of `1` for bucket arithmetic but this would be caught by the size check since the control byte array will be at least as long as the bucket array's "virtual" size.

Alternatively, we could only limit `ctrl_offset` to `isize::MAX` since all pointer arithmetic happens with `ctrl_offset` as a root. While ZST buckets could break `ctrl` accessing logic for bucket counts greater than `isize::MAX - Group::WIDTH`, `capacity_to_buckets` limits the bucket count users can *directly* request to `isize::MAX / 2`. We would just have to ensure that all other calls to the function also respect this limit.

Afaik, `RawTableInner::new_in` and `RawTableInner::new_uninitialized` are the only two methods capable of creating a new table with a different capacity so it's probably best to put the relevant checks there.

Thoughts?
