### ISSUE TITLE
Implement From<[T; N]> for HashSet<T>

### ISSUE THREAD

**Issue by 4LT** [rust-lang/hashbrown#297]
Hashbrown's HashSet does not implement the `From` trait for arrays, while `std::collections::HashSet` (as of 1.56) does.

As such, HashSet is currently not a drop-in replacement.

**Comment by Amanieu** [comment]
I would be happy to accept a PR for this if you are interested in contributing!

**Comment by 4LT** [comment]
Yeah, I might as well take a crack at it

**Comment by 4LT** [comment]
Closing because #298  was merged
