### ISSUE TITLE
Insert operations scan twice?

### ISSUE THREAD

**Issue by the8472** [rust-lang/hashbrown#300]
I'm looking for a way to insert a `&T` and only clone it when it doesn't exist yet. As far as I can tell every existing API for that scans the table twice, once to check if an item exists (going through `RawTable::find` one way or another) and then looking for a slot to insert (`RawTable::find_insert_slot`).

I'm probably overlooking something, but wouldn't it be more efficient to perform a single probe sequence that remembers a potential insert slot and keeps scanning for an existing item and then returns both?

**Comment by Amanieu** [comment]
This was attempted in #277 but the results were inconclusive. The problem is that a separate SIMD mask is needed to search for an empty bucket than is used to search for one matching a specific hash. This makes the main search loop more complex.
