### ISSUE TITLE
Sync implementation constraints for RawOccupiedEntryMut

### ISSUE THREAD

**Issue by ajtribick** [rust-lang/hashbrown#302]
The implementation of sync for `RawOccupiedEntryMut` looks like

```rust
unsafe impl<K, V, S, A> Sync for RawOccupiedEntryMut<'_, K, V, S, A>
where
    K: Sync,
    V: Sync,
    A: Send + Allocator + Clone,
{
}
```

Is the requirement that `A` be `Send` correct here, or should this be `Sync`? E.g. the equivalent implementation on `OccupiedEntry` requires `A: Sync + Allocator + Clone`.

**Comment by Amanieu** [comment]
Nice catch, that should be `A: Sync + Allocator + Clone`.

**Comment by Amanieu** [comment]
In fact, this is also missing a `S: Sync` bound (and for the `Send` impl too).

**Comment by Amanieu** [comment]
I've opened #303 which should fix all existing `Send`/Sync` bounds.
