### ISSUE TITLE
coverage regression in hashbrown 0.12.0

### ISSUE THREAD

**Issue by tabokie** [rust-lang/hashbrown#313]
Coverage report from [grcov](https://github.com/mozilla/grcov) is lost after upgrading to hashbrown 0.12.0.

The PR to upgrade hashbrown: https://github.com/tikv/raft-engine/pull/178
The PR to revert the upgrade: https://github.com/tikv/raft-engine/pull/197

**Comment by Amanieu** [comment]
I don't see what the problem is.

**Comment by tabokie** [comment]
As you should see, https://github.com/tikv/raft-engine/pull/178 updates hashbrown and the codecov stops reporting via comment (and several commits afterwards). After I reverted the update in https://github.com/tikv/raft-engine/pull/197, coverage report is back on.

I can't reproduce this locally. And this issue magically goes away just now in this newly triggered update PR: https://github.com/tikv/raft-engine/pull/198. So maybe it's just a glitch with codecov. Closing this for now.
