### ISSUE TITLE
Question: How to see the assembly code of this lib?

### ISSUE THREAD

**Issue by ShuiRuTian** [rust-lang/hashbrown#318]
This might be a stupid question....

Why I need assembly code:
I am implementing  SwissTable for C#(heavily reference this distinguished lib), but the benchmark result is slow. I do not know whether it is the benchmark problem or I have done something wrong or the C# language design limitation. Currently the bottle neck is `find_insert_slot` in my C# implementation. So I want to have a look at the assembly code.

What I have tried:
``` ps1
cargo rustc --release -- --emit asm
cargo asm
```

The first command generated a lot of files under `target/release/deps`, but it feels like the real data is hidden in .rmeta and .rlib files.
And the second command should list all functions that could be shown, in which I only find one related to `hashbrown`.

Have I done something wrong? How could I read the assembly code of this lib?

**Comment by Amanieu** [comment]
Most of the functions are inlined, so the best way is to create a separate cargo project which uses hashbrown as a dependency and simply calls one function. You can then get the disassembly for that function.

See this example on the playground: https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=b390a0acf79a51ecd71687b46c5e8866
