### ISSUE TITLE
Bug in `RawOccupiedEntryMut::get_key_value`

### ISSUE THREAD

**Issue by JustForFun88** [rust-lang/hashbrown#337]
Does this seem like a bug, or am I missing something?  There is no need for mutable borrowing here.
```rust
impl<'a, K, V, S, A: Allocator + Clone> RawOccupiedEntryMut<'a, K, V, S, A> {
    /// Gets a reference to the key and value in the entry.
    #[cfg_attr(feature = "inline-more", inline)]
    pub fn get_key_value(&mut self) -> (&K, &V) {
        unsafe {
            let &(ref key, ref value) = self.elem.as_ref();
            (key, value)
        }
    }
}
```
I noticed it when I wrote an example for this function, and the compiler: `make the variable mutable`!  Me: wait, what😂?

**Comment by Amanieu** [comment]
Hmm yes, that does seem like a bug. The `std` API has the same issue: https://doc.rust-lang.org/nightly/std/collections/hash_map/struct.RawOccupiedEntryMut.html#method.get_key_value

A PR would be welcome!

**Comment by JustForFun88** [comment]
> Hmm yes, that does seem like a bug. The `std` API has the same issue: https://doc.rust-lang.org/nightly/std/collections/hash_map/struct.RawOccupiedEntryMut.html#method.get_key_value
> 
> A PR would be welcome!

I will correct the funtion inside the pull request #331
