### ISSUE TITLE
is bug with  RawTable?

### ISSUE THREAD

**Issue by Amdahl-rs** [rust-lang/hashbrown#344]
Group  vec![124_i32, 123, 1, 8, 2, 1, 8, 2, 123, 124]  ， expects map len is 5 but 8 ？？
 
```
fn raw_table_test() -> Result<()> {
    let map = &mut hashbrown::raw::RawTable::<(usize, usize)>::new();
    let value = vec![124_i32, 123, 1, 8, 2, 1, 8, 2, 123, 124];
    let state = &RandomState::default();
    value.iter().enumerate().for_each(|(i, data)| {
        let h = <i32>::get_hash(&data, state);
        let ent = map.get(h, |(x, y)| unsafe { value.get_unchecked(*x) == data });
        match ent {
            Some(v) => {}
            None => {
                map.insert(h, (i, i), |_| h);
            }
        };
    });
    let len = map.len();
    assert_eq!(len ,5);
    Ok(())
}

```
**output**
`panicked at 'assertion failed: `(left == right)`
 left: `8`,
 right: `5`'`

**Comment by Amanieu** [comment]
I think this line is wrong:
```rust
let ent = map.get(h, |(x, y)| unsafe { value.get_unchecked(*x) == data });
```
It should be:
```rust
let ent = map.get(h, |(x, y)| *x == data);
```

**Comment by Amdahl-rs** [comment]
map.insert(h, (i, i), |_| h)  ;
map save data  is  values   index

**Comment by Amanieu** [comment]
The hasher function (`|_| h`) that you passed to `insert` is incorrect. This function is used when growing the table and is applied to all existing elements.

**Comment by Amdahl-rs** [comment]
Thank you very much for  reply, I understand.

**Comment by Amdahl-rs** [comment]
` map.insert(hash_code, (hash_code, i), |(hash_key,index)| hash_key);`

To avoid repeated hashes, only hashes can be saved_ code.
It's strange why with_ Capacity (size) can be correct. Is it because buckets are pre allocated ?

**Comment by Amanieu** [comment]
The hasher function is only used if the table needs to grow.

**Comment by Amdahl-rs** [comment]
Thank you very much
