### ISSUE TITLE
Lookup value without `Borrow` implementation

### ISSUE THREAD

**Issue by timothee-haudebourg** [rust-lang/hashbrown#345]
I have a recurring problem with this library (and the standard library) on the signature of lookup methods such as `HashMap::get(&self, key: &Q)` that require the key type `K` to implement `K: Borrow<Q>`. I came across many cases where this is a limitation. For instance consider a map where the key type is as follows:
```rust
enum Key {
  String(String)
  Number(i32)
}
```
This type owns the data. But if you want to build a string key by only borrowing the string (which itself may not be in a `Key`), a nice solution is to define a `KeyRef` type as follows
```rust
enum KeyRef<'a> {
  String(&'a str)
  Number(i32)
}
```
Now because the string is wrapped inside an `enum` type, there is no way to have `Key: Borrow<KeyRef>`, even though both types are semantically very close, can have the same hash function, have a straight forward comparison function, etc. But because we can't implement `Key: Borrow<KeyRef>`, we can't use `KeyRef` as a key in `HashMap::get`, which is very annoying. The only solution in this case is to clone the data from `KeyRef` to build a `Key` and then use `HashMap::get`.

There are some successful hash map implementations out there that have solved this issue already. For instance, the [`indexmap`](https://crates.io/crates/indexmap) library introduces an [`Equivalent`](https://docs.rs/indexmap/latest/indexmap/trait.Equivalent.html) trait that replaces the `Borrow` bound and instead requires `Q: Equivalent<K>`. The only provided implementation is based on `Borrow`:
```rust
impl<Q: ?Sized, K: ?Sized> Equivalent<K> for Q where
    Q: Eq,
    K: Borrow<Q>
```
This makes this little difference transparent when the `K: Borrow<Q>` implementation exists, but also allows for more complicated scenarios to work by adding an `Equivalent` implementation.

I know introducing a new trait is sometimes not wanted, but in this case it could solve a recurring problem, that I'm sure have be encountered by many people, justifying its introduction in the `indexmap` library.

**Comment by Amanieu** [comment]
I'd be happy to include support for `Equivalent` in hashbrown! Would you be interested in writing up a PR for this?

**Comment by timothee-haudebourg** [comment]
The only issue is with the `EntryRef` API, which requires `K: Borrow<Q>` not only for comparison. I could adapt the API, in particular by exposing the `KeyOrRef` type, but not without major changes, so for now I'll just keep it as it is.

**Comment by timothee-haudebourg** [comment]
Actually I'm not sure if adding a trait such as `Equivalent` should be considered as a major change or not, since it has a blanket implementation that covers all the cases it replaces.

**Comment by Imberflur** [comment]
Is this issue ready to be closed?
