### ISSUE TITLE
`RawIterHash` is unnecessarily restrictive

### ISSUE THREAD

**Issue by moulins** [rust-lang/hashbrown#415]
The documentation on the (unsafe) `RawTable::iter_hash` method says the following:
> It is up to the caller to ensure that the `RawTable` outlives the `RawIterHash`. Because we cannot make the next method unsafe on the `RawIterHash` struct, we have to make the `iter_hash` method unsafe.

But this is actually false: `RawIterHash` immutably borrows the table, preventing concurrent mutations and any possible unsoundness (at least without further manipulating the yielded buckets).

Either `iter_hash` should become safe, and the documentation updated, or `RawIterHash` should keep a pointer to the relevant `RawTable` parts instead of a reference, like `RawIter` already does (in my opinion, the best solution).

**Comment by Amanieu** [comment]
I believe the only part of the table that needs to be kept is `bucket_mask`. I would be happy to accept a PR which removes the lifetime from `RawIterHash`.
