### ISSUE TITLE
Is hashbrown::HashMap  thread safe when storing a int type，at the same time，multi thread read，and only one thread update/insert/delete ?

### ISSUE THREAD

**Issue by glenn-wang** [rust-lang/hashbrown#441]
Reading old values is acceptable.

**Comment by Amanieu** [comment]
No, you cannot read anything from the map if another thread is concurrently modifying it. This is not allowed by Rust's safety invariants, and it is not not supported by the implementation.

To support concurrent reads, you would need a specialized concurrent hash table such as dashmap.
