### ISSUE TITLE
Why the identity function can be used as unlikely function? 

### ISSUE THREAD

**Issue by YjyJeff** [rust-lang/hashbrown#482]
According to the [code](https://github.com/rust-lang/hashbrown/blob/master/src/raw/mod.rs#L54), both `likely` and `unlikely` functions use the `identity` function. Why this function can be used as `unlikely`? How it works? How the compiler distinguish `likely` from `unlikely`? 

Thanks in advance

**Comment by exrok** [comment]
The compiler can't distinguish them. 

Without the `nightly` feature the `likely,unlikely` functions do nothing and are simply the identify function as you observed. 

But with the nightly feature...

```rust
#[cfg(feature = "nightly")]
use core::intrinsics::{likely, unlikely};
```
the actual intrinsics are used, which are still nightly only: https://doc.rust-lang.org/stable/core/intrinsics/fn.likely.html

**Comment by YjyJeff** [comment]
Ok. I am looking for the implementation of the `likely` and `unlikely` in stable. Some other links said that hashbrown has a stable implementation of these two functions. I noticed the implementation has changed recently. 

So in the current stable rust, the old implementation does not work and we can not achieve it now? @exrok

**Comment by exrok** [comment]
Correct that is the my current understanding. I am not aware of a stable implementation of the likely and unlikely. You could try the olds impls from hashbrown (removed here https://github.com/rust-lang/hashbrown/commit/d677fd42df6978522045a9561242588ef970ed0c) the logic behind seems sounds it is just a question of if they help LLVM consistently. 

Sometimes even the unstable intrinsics don't help consistently: https://github.com/rust-lang/rust/issues/88767

Also note, the current likely/unlikely intrinsics are currently marked "perma-unstable", so don't expect them to stabilize soon: https://github.com/rust-lang/rust/issues/26179#issuecomment-989056000 

In terms of stable solutions I think the closest would be PGO: https://doc.rust-lang.org/rustc/profile-guided-optimization.html
But that only helps if your the one building the application and complicates the build procedure.
