### ISSUE TITLE
Build breaks on nightly due to use of `stdsimd` rust feature in ahash 0.8.6

### ISSUE THREAD

**Issue by sdd** [rust-lang/hashbrown#499]
The `stdsimd`rust feature has been removed from nightly Rust as of 1.78.0-nightly (f067fd608 2024-02-05).

Ahash 0.8.6 attempts to enable this rust feature when its own `stdsimd` feature is enabled, as happens in hashbrown 0.14.3. This causes builds to break on nightly.

**Comment by s1341** [comment]
has a new version of hashbrown with this change been released?

**Comment by Amanieu** [comment]
Not yet, but it isn't necessary: just run `cargo update` to get the latest version of ahash.
