### ISSUE TITLE
Consider returning to 1.63.0 MSRV

### ISSUE THREAD

**Issue by tnull** [rust-lang/hashbrown#504]
Recently, `ahash` bumped their MSRV to 1.72.0 in a patch release, [which is really unfortunate](https://github.com/tkaitchuck/aHash/issues/207). 

It seems that `hashbrown` followed a similar pattern in #502 and silently bumped the `rustc` version in CI to 1.72.0.

Rather than also bumping MSRV (let alone in a patch release), it would be great if `hashbrown` could revert to a 1.63.0 MSRV, find a workaround, and make recommendations to downstream users that may or may not pin the violating `ahash` dependency.

It would be great if this path could at least be considered.

**Comment by Amanieu** [comment]
There's nothing that can be done in hashbrown itself, only in ahash. You could try submitting a PR to restore 1.63 compatibility there by using a build script to detect the rustc version.
