### ISSUE TITLE
update to ahash 0.8.7 or after to use new stdsimd feature portable_simd

### ISSUE THREAD

**Issue by jianshu93** [rust-lang/hashbrown#514]
Dear Hashbrown team, 

It seems when rely ahash for high performance, ahash 0.8.6 is not compatible with newest nightly rust 1.78 which is now portable_simd for the old  stdsimd features. 0.8.7 or later should be fine. Can you please update it here at GitHub and also to the crates.io when the feature stables?

Thanks,

Jianshu

**Comment by Amanieu** [comment]
You don't need to wait for a new release of hashbrown, just run `cargo update ahash` to update ahash to the latest version.
