### ISSUE TITLE
Storing the bumpalo buffer (or alternative) and reading back from it ?

### ISSUE THREAD

**Issue by ThomasCartier** [rust-lang/hashbrown#598]
Hi,

I need to store the hashmap key/values on disk and retrieve it later, without reinserting everything.
new_in + bumpalo seem to make it for the allocation part, but I am not sure how it can read from this buffer again, once the hashmap has been deleted.
A kind of `from_buffer` would be handy.
Or maybe there is an existing solution I missed?

**Comment by Amanieu** [comment]
`hashbrown` doesn't guarantee a stable layout and is not suitable for on-disk storage. You may want to consider `rkyv` for this instead.
