### ISSUE TITLE
Move to the rust-lang org

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/hashbrown#68]
As https://github.com/rust-lang/rust/pull/58623 has landed we should probably move this to the rust-lang org. If you add me or @pietroalbini as admins to this repo, we can do this move (I think you need to have admin on rust-lang to move a crate there)

**Comment by pietroalbini** [comment]
You can't add people as administrators to personal projects: you have to transfer the repo to an org owner's account, and then the org owner can transfer the repo to the org.

**Comment by Manishearth** [comment]
Oh, damn. Uh, in that case please transfer to one of us, I guess?

**Comment by Manishearth** [comment]
Done, thanks!

**Comment by Manishearth** [comment]
The libs team (and various bot teams) have access, lmk if perms need to be tweaked
