### ISSUE TITLE
Assertion panics

### ISSUE THREAD

**Issue by elichai** [rust-lang/hashbrown#79]
Hi,
I'm still trying to figure out why it happens (it's not easy to get backtrace on a panic without std)
But I'm getting a panic here:
```
thread panicked at 'Box<Any>', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.3.0/src/raw/mod.rs:1078:9
```

If that's a known thing or if you have any ideas help is welcome :)

Thanks!

https://github.com/rust-lang/hashbrown/blob/4368aa436cfcb2160bc0efddd49fc073e4a486a0/src/raw/mod.rs#L1078

**Comment by Amanieu** [comment]
Your allocator is not returning properly aligned memory.

**Comment by elichai** [comment]
@Amanieu you have any idea what can cause that? can a memory leak somewhere cause this? maybe something else?

**Comment by Amanieu** [comment]
It's a bug in whatever allocator you are using in no_std.
