### ISSUE TITLE
Remove bias in benchmarks

### ISSUE THREAD

**Issue by tkaitchuck** [rust-lang/hashbrown#81]
As mentioned briefly in: https://github.com/rust-lang/hashbrown/pull/71
The benchmarks at present rely on sequential integers. This leads to a serious bias. If the hashmap grows every time it reaches its capacity limit, by the birthday paradox there should be a number of bucket collisions along the way. Hashbrown performs well in this case by storing one byte of the hash code to attempt to resolve the hash collision without having to resort to comparing the keys. 

Unfortunately despite the fact that this code path is expected to be common in real life (See footnote) and important to the overall performance of the map, **none** of the benchmarks presently ever exercise it. (This is because the FxHash is just a single multiplication, so the increasing integers always have evenly spaced low order bits.)

If the benchmarks were changed to instead use random keys, this code path would be exercised and the performance numbers would be more meaningful. 

Footnote: _(back of the envelope math based on the formula here http://matt.might.net/articles/counting-hash-collisions/ is that as n approaches d and they both get larger the probably of a bucket collisions approaches e^-1 or ~36% when the map is filled. When it is midway between having being resized and needing to be resized again it is ~25%. So we can expect to need to compare the stored byte about a quarter of time.)_

**Comment by edre** [comment]
This has been mostly solved by 594a2a7. I added a random distribution which should be hard for any hash to mess up, and it does about as well as the consecutive integers. I re-added the pessimistic case of a high-bit-range distribution, and Fx does pretty badly there.

**Comment by Amanieu** [comment]
I'm closing this for now, @tkaitchuck please reopen if you feel the new benchmarks are still unsatisfactory.
