### ISSUE TITLE
Why is RawOccupiedEntryMut !Sync?

### ISSUE THREAD

**Issue by kyren** [rust-lang/hashbrown#99]
`Entry` is `Sync` if `K`, `V`, and `S` are all `Sync`, and `RawVacantEntryMut` is also `Sync` in the same way, but I'm not sure why `RawOccupiedEntryMut` is always `!Sync`?

I ran into this because I'm [porting](https://github.com/kyren/hashlink) `linked-hash-map` to be on top of hashbrown's raw-entry API, and I couldn't figure out why this type would need to be `!Sync` (It also makes `RawEntryMut` `!Sync`).

It's definitely possible I'm missing something, so this is genuinely meant as a question.

**Comment by Amanieu** [comment]
I believe this is simply an oversight, and `RawVacantEntryMut` should have manual `Send` and `Sync` impls like `OccupiedEntry` has. Would you be willing to submit a PR?

**Comment by kyren** [comment]
Sure thing!
